#!/usr/bin/env python3
"""Appends one CHANGELOG.md entry for a just-merged PR.

Run by .github/workflows/changelog.yml. Reads PR_NUMBER, PR_TITLE, PR_BODY,
and MERGED_AT from the environment rather than interpolating them into a
shell command - those values come from the PR itself (an external
contributor's PR title/body included), so they're untrusted input and must
never be substituted directly into a shell string.
"""
import os
import re
from pathlib import Path

CHANGELOG = Path("CHANGELOG.md")

FOOTER_RE = re.compile(r"\n?-{3,}\n_Generated by \[Claude Code\].*$", re.DOTALL)


def clean_body(body: str) -> str:
    # Strip the Claude Code attribution footer - redundant once this text
    # sits under its own dated heading here. Only matches the exact footer
    # pattern (a "---" rule directly followed by the attribution line), so
    # an unrelated "---" elsewhere in the PR body is left alone.
    body = FOOTER_RE.sub("", body).strip()

    # PR bodies commonly use "## Summary" / "## Test plan" as their own
    # top-level headings. Demote those one level so they read as
    # sub-sections of this entry, not as sibling changelog entries under
    # the date heading this script just added.
    body = re.sub(r"(?m)^## ", "### ", body)

    return body


def main() -> None:
    number = os.environ["PR_NUMBER"]
    title = os.environ["PR_TITLE"]
    body = clean_body(os.environ.get("PR_BODY") or "")
    date = os.environ["MERGED_AT"][:10]

    entry = f"## {date} - {title} (#{number})\n\n{body}\n".rstrip() + "\n"

    content = CHANGELOG.read_text(encoding="utf-8") if CHANGELOG.exists() else "# Changelog\n"

    marker = "\n## "
    idx = content.find(marker)
    if idx == -1:
        new_content = content.rstrip() + "\n\n" + entry
    else:
        new_content = content[: idx + 1].rstrip() + "\n\n" + entry + "\n" + content[idx + 1 :]

    CHANGELOG.write_text(new_content, encoding="utf-8")


if __name__ == "__main__":
    main()
